# Generated by Django 2.2.6 on 2019-10-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='avatar',
            field=models.ImageField(default='static/images/undraw_female_avatar_l3ey.svg', upload_to='images/%Y/%m/%d/'),
        ),
    ]
