# Generated by Django 2.2.6 on 2019-10-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapost', '0002_utilisateur_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={},
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='name',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_upd',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='image',
            field=models.ImageField(default='useravatar.png', upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='nom',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='phone',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
